FROM registry.access.redhat.com/ubi8/python-36
LABEL maintainer="Serhii Kryzhnii skryzhni@redhat.com"
RUN pip3 install --upgrade pip && pip3 install tox 

ADD . /package
WORKDIR /package

USER root
RUN mkdir /package/.tox
RUN chown 1001:0 /package/.tox
USER 1001

CMD ["tox"]
